#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'html'
  formatter: stylish
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# File Options
files:
  include: 'src/**/*.scss'
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq
  no-vendor-prefixes: 2
  no-warn: 2
  no-debug: 2
  no-ids: 2
  no-important: 2
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - 2
    -
      order: alphabetical
  variable-for-property:
    - 2
    -
      properties:
        - margin
        - content